<?php

use App\Livewire\Admin\Companies as AdminCompanies;
use App\Livewire\Admin\PeriodLock as AdminPeriodLock;
use App\Livewire\Admin\Users as AdminUsers;
use App\Http\Controllers\AuditLogPrintController;
use App\Http\Controllers\CompanyLogoController;
use App\Http\Controllers\ContactDocumentController;
use App\Http\Controllers\ContactPhotoController;
use App\Livewire\Admin\AuditLogs\Index as AdminAuditLogs;
use App\Livewire\Admin\Credentials\Index as AdminCredentials;
use App\Livewire\Categories\Index as CategoriesIndex;
use App\Livewire\Contacts\Form as ContactsForm;
use App\Livewire\Contacts\Index as ContactsIndex;
use App\Livewire\CostCenters\Index as CostCentersIndex;
use App\Livewire\CropSeasons\Index as CropSeasonsIndex;
use App\Livewire\Currencies\Index as CurrenciesIndex;
use App\Livewire\FinancialAccounts\Index as FinancialAccountsIndex;
use App\Http\Controllers\FinancialEntryReceiptController;
use App\Livewire\FinancialEntries\Index as FinancialEntriesIndex;
use App\Livewire\Hr\Index as HrIndex;
use App\Livewire\Hr\Profile as HrProfile;
use App\Livewire\ProductCategories\Index as ProductCategoriesIndex;
use App\Livewire\Products\Index as ProductsIndex;
use App\Livewire\ProductTaxProfiles\Index as ProductTaxProfilesIndex;
use App\Livewire\RuralActivities\Index as RuralActivitiesIndex;
use App\Livewire\RuralAssets\Index as RuralAssetsIndex;
use App\Livewire\RuralFields\Index as RuralFieldsIndex;
use App\Livewire\RuralProperties\Index as RuralPropertiesIndex;
use App\Livewire\Sales\Index as SalesIndex;
use App\Livewire\StockLocations\Index as StockLocationsIndex;
use App\Livewire\StockMovements\Index as StockMovementsIndex;
use App\Livewire\Reports\AccountStatement as ReportsAccountStatement;
use App\Livewire\Reports\Analytical as ReportsAnalytical;
use App\Livewire\Reports\CashFlow as ReportsCashFlow;
use App\Livewire\Reports\CashForecast as ReportsCashForecast;
use App\Livewire\Reports\CostCenters as ReportsCostCenters;
use App\Livewire\Reports\Dre as ReportsDre;
use App\Livewire\Reports\Index as ReportsIndex;
use App\Livewire\Reports\Payables as ReportsPayables;
use App\Livewire\Reports\Receivables as ReportsReceivables;
use App\Livewire\Reports\Registrations as ReportsRegistrations;
use App\Livewire\Reports\RuralCosts as ReportsRuralCosts;
use App\Livewire\Tasks\Index as TasksIndex;
use Illuminate\Support\Facades\Route;

// Rotas das telas de negócio (fora do que o Breeze gera). Este arquivo é
// carregado a partir de bootstrap/app.php (bloco `then:`).

Route::middleware(['web', 'auth'])->group(function () {
    Route::get('/financeiro/contas', FinancialAccountsIndex::class)->name('financial-accounts.index');
    Route::get('/financeiro/categorias', CategoriesIndex::class)->name('categories.index');
    Route::get('/financeiro/centros-de-custo', CostCentersIndex::class)->name('cost-centers.index');
    Route::get('/financeiro/moedas', CurrenciesIndex::class)->name('currencies.index');
    Route::get('/financeiro/lancamentos', FinancialEntriesIndex::class)->name('financial-entries.index');
    Route::get('/financeiro/lancamentos/{financialEntry}/recibo', [FinancialEntryReceiptController::class, 'show'])->name('financial-entries.receipt');
    Route::get('/contatos', ContactsIndex::class)->name('contacts.index');
    Route::get('/contatos/novo', ContactsForm::class)->name('contacts.create');
    Route::get('/contatos/{contact}/editar', ContactsForm::class)->name('contacts.edit');
    Route::get('/contatos/documentos/{contactDocument}', [ContactDocumentController::class, 'download'])->name('contacts.documents.download');
    Route::get('/contatos/{contact}/foto', [ContactPhotoController::class, 'show'])->name('contacts.photo');
    Route::get('/agenda', TasksIndex::class)->name('tasks.index');
    Route::get('/rh', HrIndex::class)->name('hr.index');
    Route::get('/rh/{contact}/ficha', HrProfile::class)->name('hr.profile');
    Route::get('/estoque/categorias', ProductCategoriesIndex::class)->name('product-categories.index');
    Route::get('/estoque/produtos', ProductsIndex::class)->name('products.index');
    Route::get('/estoque/locais', StockLocationsIndex::class)->name('stock-locations.index');
    Route::get('/estoque/movimentacoes', StockMovementsIndex::class)->name('stock-movements.index');
    Route::get('/vendas/pedidos', SalesIndex::class)->name('sales.index');
    Route::get('/vendas/perfis-tributarios', ProductTaxProfilesIndex::class)->name('product-tax-profiles.index');
    Route::get('/rural/propriedades', RuralPropertiesIndex::class)->name('rural-properties.index');
    Route::get('/rural/talhoes', RuralFieldsIndex::class)->name('rural-fields.index');
    Route::get('/rural/ativos', RuralAssetsIndex::class)->name('rural-assets.index');
    Route::get('/rural/safras', CropSeasonsIndex::class)->name('crop-seasons.index');
    Route::get('/rural/atividades', RuralActivitiesIndex::class)->name('rural-activities.index');
    Route::get('/admin/empresas', AdminCompanies::class)->name('admin.companies.index');
    Route::get('/admin/empresas/{company}/logo', [CompanyLogoController::class, 'show'])->name('admin.companies.logo');
    Route::get('/admin/usuarios', AdminUsers::class)->name('admin.users.index');
    Route::get('/admin/fechamento', AdminPeriodLock::class)->name('admin.period-lock.index');
    Route::get('/admin/credenciais', AdminCredentials::class)->name('admin.credentials.index');
    Route::get('/admin/auditoria', AdminAuditLogs::class)->name('admin.audit.index');
    Route::get('/admin/auditoria/imprimir', [AuditLogPrintController::class, 'show'])->name('admin.audit.print');

    Route::get('/relatorios', ReportsIndex::class)->name('reports.index');
    Route::get('/relatorios/dre', ReportsDre::class)->name('reports.dre');
    Route::get('/relatorios/fluxo-de-caixa', ReportsCashFlow::class)->name('reports.cash-flow');
    Route::get('/relatorios/contas-a-pagar', ReportsPayables::class)->name('reports.payables');
    Route::get('/relatorios/contas-a-receber', ReportsReceivables::class)->name('reports.receivables');
    Route::get('/relatorios/centros-de-custo', ReportsCostCenters::class)->name('reports.cost-centers');
    Route::get('/relatorios/analitico', ReportsAnalytical::class)->name('reports.analytical');
    Route::get('/relatorios/previsao-de-caixa', ReportsCashForecast::class)->name('reports.cash-forecast');
    Route::get('/relatorios/extrato-de-conta', ReportsAccountStatement::class)->name('reports.account-statement');
    Route::get('/relatorios/cadastrais', ReportsRegistrations::class)->name('reports.registrations');
    Route::get('/relatorios/custos-rurais', ReportsRuralCosts::class)->name('reports.rural-costs');
});
